name: backdate-linter
on:
  workflow_dispatch:
    inputs:
      date:
        description: ISO-8601 timestamp (e.g., 2025-10-21T10:00:00+02:00)
        required: true
        default: "2025-10-21T10:00:00+02:00"

permissions:
  contents: write

jobs:
  backdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create file (skip if exists)
        run: |
          if [ -f src/lint_metric_spec.py ]; then echo "Already exists, nothing to do."; exit 0; fi
          mkdir -p src
          cat > src/lint_metric_spec.py <<'PY'
import sys, yaml, glob
REQUIRED = {"name","owner","description","grain","type","formula"}
def check(path):
    with open(path,"r",encoding="utf-8") as f:
        d = yaml.safe_load(f)
    assert isinstance(d, dict) and "metric" in d and isinstance(d["metric"], dict), "root must contain 'metric' mapping"
    missing = REQUIRED - set(d["metric"].keys())
    assert not missing, f"missing keys: {sorted(missing)}"

if __name__ == "__main__":
    ok=True
    for p in glob.glob("templates/*.yaml"):
        try:
            check(p); print("OK:", p)
        except Exception as e:
            print("FAIL:", p, "->", e); ok=False
    sys.exit(0 if ok else 1)
PY
      - name: Commit with backdated timestamp
        run: |
          git add src/lint_metric_spec.py
          export GIT_AUTHOR_DATE="${{ github.event.inputs.date }}"
          export GIT_COMMITTER_DATE="${{ github.event.inputs.date }}"
          git commit -m "feat(metric-hunter): add spec linter" || echo "No changes to commit."
          git push || echo "Nothing pushed."
