name: ci
on: [push, pull_request]
jobs:
  check-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Validate template YAML
        run: |
          python - <<'PY'
          import yaml, glob, sys
          ok = True
          for p in glob.glob("templates/*.yaml"):
              print("Checking", p)
              try:
                  with open(p, "r", encoding="utf-8") as f:
                      yaml.safe_load(f)
              except Exception as e:
                  print("YAML error in", p, "->", e)
                  with open(p, "r", encoding="utf-8") as f:
                      print("--- first 10 lines ---")
                      for i, line in enumerate(f.readlines()[:10], 1):
                          print(f"{i:02d}: {line.rstrip()}")
                  ok = False
          sys.exit(0 if ok else 1)
          PY
